export default {
	access_token: "EAACEdEose0cBAB2vwEUsduF0UBHfZACrZBZAhZBjZCKa2YQWJmjAtqeLDbhVElrlegjZANk3NVP6QdQxq6ynXL33nQkOwVe6gCdi60oXAcsxfwZByAreZAla4hLpOZBN3FHeSbGs7rXAwzcNdqSCjAo4SIDPxzb5WeG8uYXNPH0ygTwZDZD"
}
